---
title: "Assignment 2 FE-515"
author: "Akshay Pradeep Patade"
date: "2023-03-12"
output:
  pdf_document: default
  html_document: default
---

---

# Question 1: (50 points)

## 1.1 

```{r}
df <- read.csv("JPM.csv")
df
df[,1] <- as.Date(df[,1])

```

## 1.2


```{r}


plot(df$Date, df$Adj.Close, type="l", col="red",
     xlab="Date", ylab="Adjusted Close Price", main="JPM")

```

## 1.3 


```{r}


plot(df$Open, df$Close, xlab="Open Price", ylab="Close Price", main="JPM",
     col="blue", pch=20)

```

## 1.4 


```{r}

cuts <- cut(df$Adj.Close, breaks=4, labels=c("Low", "Medium", "High", "Very High"))

barplot(table(cuts), xlab="Adjusted Close Price Intervals", ylab="Frequency", main="JPM")

```

## 1.5


```{r}

boxplot(df$Volume ~ cuts, xlab="Adjusted Close Price Intervals", ylab="Volume", main="JPM")

```

## 1.6

```{r}
par(mfrow=c(2,2))

plot(df$Date, df$Adj.Close, type="l", col="red",
     xlab="Date", ylab="Adjusted Close Price", main="JPM")

plot(df$Open, df$Close, xlab="Open Price", ylab="Close Price", main="JPM",
     col="blue", pch=20)

cuts <- cut(df$Adj.Close, breaks=4, labels=c("Low", "Medium", "High", "Very High"))

barplot(table(cuts), xlab="Adjusted Close Price Intervals", ylab="Frequency", main="JPM")


boxplot(df$Volume ~ cuts, xlab="Adjusted Close Price Intervals", ylab="Volume", main="JPM")

```

## 2

```{r}

N <- 1000000


x <- runif(N)
y <- runif(N)
z <- runif(N)


count <- sum(x^2 + y^2 + z^2 <= 1 & x >= 0 & y >= 0 & z >= 0)


vol <- 8 * count / N
volume <- vol * (4*pi/3)

print(volume)

```

